language: node_js
node_js:
- '5'
branches:
  only:
  - "/^v[0-9]/"
before_deploy:
- npm run build
addons:
  code_climate:
    repo_token: #get repo_token from https://codeclimate.com/dashboard
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- npm run coverage
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  skip_cleanup: true
  on:
    tags: true
